version: '3.3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - ./.bashrc-docker:/root/.bashrc
      - ./ros_packages/:/opt/ros/dev_ws/src
    image: 'dev_image:foxy'
    tty: true
    stdin_open: true
    container_name: 'dev'
    privileged: true
    network_mode: host
  piobuilder:
    build:
      context: .
      dockerfile: Dockerfile.PIO
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev:/dev
      - ./.bashrc-docker:/root/.bashrc
      - ./ros_packages/:/opt/ros/dev_ws/src
      - ./platformio_projects/:/opt/ros/dev_ws/pio_projs
    image: 'dev_image:foxy'
    tty: true
    stdin_open: true
    container_name: 'dev'
    privileged: true
    network_mode: host
  lsp:
    build:
      context: .
      dockerfile: Dockerfile.LSP
    image: "dev_image_lsp:foxy"
