version: "3.3"
services:
        dev:
                build:
                        context: .
                        dockerfile: Dockerfile
                environment:
                        - DISPLAY=${DISPLAY}
                volumes:
                        - /dev:/dev
                        - ./.bashrc-docker:/root/.bashrc
                        - ./ros_packages/:/opt/ros/dev_ws/src
                image: "dev_image:foxy"
                tty: true
                stdin_open: true
                container_name: "dev"
                privileged: true
        uros:
                image: "microros/micro-ros-agent:foxy"
                command: serial --dev <TEENSYNAME>
                volumes:
                        - /dev:/dev
                container_name: "uros"
