FROM ros:foxy

RUN apt-get -y update 
RUN apt-get -y upgrade
RUN apt-get install -y build-essential net-tools vim wget 
RUN apt-get install -y nano
RUN apt-get install -y python3-pip
RUN pip3 install Cython
RUN pip3 install sbp
RUN pip3 install numpy --upgrade
