version: "3.3"
services:
        dev:
                build:
                        context: .
                        dockerfile: Dockerfile-Noetic
                volumes:
                        - /dev:/dev
                        - ./.bashrc:/root/.bashrc
                        - ./catkin_ws:/root/catkin_ws
                image: "dev_image:noetic"
                tty: true
                container_name: "dev"
                privileged: true
                working_dir: /root
