version: "3.3"
services:
        dev:
                build:
                        context: .
                        dockerfile: Dockerfile-Galactic
                environment:
                        - DISPLAY=${DISPLAY}
                volumes:
                        - /dev:/dev
                        - ./.bashrc:/root/.bashrc
                        - ./dev_ws:/root/dev_ws
                image: "dev_image:galactic"
                tty: true
                container_name: "dev"
                privileged: true
                working_dir: /root
