#FROM ros:foxy
#
#RUN mkdir -p uros_ws
#WORKDIR uros_ws
#RUN git clone --depth 1 -b foxy https://github.com/micro-ROS/micro_ros_setup.git src/micro_ros_setup \
#&& . /opt/ros/$ROS_DISTRO/setup.sh \
#&& apt update \
#&& apt install -y ed python3-pip \
#&& rosdep update --rosdistro $ROS_DISTRO \
#&& rosdep install --from-paths src --ignore-src -y \
#&& colcon build \
#&& rm -rf log/ build/ src/* \
#&& rm -rf /var/lib/apt/lists/*
#
#RUN echo ". /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
#RUN echo ". /uros_ws/install/setup.bash" >> ~/.bashrc

FROM microros/base:foxy

WORKDIR /uros_ws
RUN . /opt/ros/$ROS_DISTRO/setup.sh \
&& . install/local_setup.sh \
&& ros2 run micro_ros_setup create_agent.sh \
&& ros2 run micro_ros_setup build_agent.sh \
&& rm -rf log/ build/ src/

COPY disable_fastdds_shm.xml /tmp/
ENV FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/disable_fastdds_shm.xml

CMD ["bash"]
