FROM ros:galactic

RUN apt -y update 
RUN apt -y upgrade
RUN apt install -y build-essential net-tools vim wget 
RUN apt install -y nano
RUN apt install -y python3-pip
RUN apt install -y ~nros-galactic-rqt*

RUN pip3 install Cython
RUN pip3 install sbp
RUN pip3 install numpy --upgrade
