version: "3.3"
services:
        dev:
                volumes:
                        - /dev:/dev
                        - ./.bashrc:/root/.bashrc
                        - ./catkin_ws:/root/catkin_ws
                image: "dukeelectricvehicles/dev:latest"
                tty: true
                container_name: "dev"
                privileged: true
                working_dir: /root
